### ISSUE TITLE
Setting Fat Feeder range to 100,000 lags out dedicated server

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Da-Technomancer/Crossroads#101]
This was discovered by one of my playtesters, so I may be missing a few details. The player set the range of a fat feeder block to 100,000, and the server crashed due to performance issues after about one minute. Setting the block back to a more reasonable number fixed the issue.

The fat feeder was inside this player's personal dimension. Running `/cofh tps` shows that that dimension was running at 0.8 TPS, while the other dimensions were running smoothly.

Crash log: https://pastebin.com/8knUCdue

**Comment by Da-Technomancer** [comment]
Let's take this one step at a time:

1. Player on a server uses a block that normally has a range of like 10
2. Player, I assume, has what they think is a genius idea to make the range cover everything
3. Player manages to bump the range of to 100,000, which not only stretches over multiple chunks, it stretches over multiple region files. It, in fact, stretches farther than most single player worlds are ever generated to
4. Player is surprised that when giving a block that normally has quite a small range a range that covers several times the length of the world and therefore queries every single entity in the entire dimension every few ticks causes lag

This is like when people build a mountain out of TNT, explode it all at once, and report it to Mojang as a bug for lagging.

I suppose I could have put a maximum range in as a sanity check?
