### ISSUE TITLE
[Suggestions] About localization and ore dict

### ISSUE THREAD

**Issue by kappa-maintainer** [Da-Technomancer/Crossroads#104]
First, some unlocalization keys of Crossroads are to common that they conflict with many other mods. It will cause translated strings to cover each other and confuse players. These keys include:
tile.alembic.name - conflict with Thaumcraft
tile.fluid_tank.name - conflict with Futurepack Mod
tile.grindstone.name - conflict with Horse Power
and so on.
A simple solution is insert modid after every keys' first word.
Second, I notice some string didn't appear in lang file as expect. These strings are tooltips, chat messages and strings appear in GUI. Enable these string to be localizable would make Crossroads can be fully translated.
Third, when install Crossroads and Thermal Expansion, TE items can use Crossroads' gears as ingredient, which should not happen. Maybe you can add a config option to disable ore dict of gears or change their ore dict to a form different from TE's(since they are two types of gears).

**Comment by Da-Technomancer** [comment]
About localization: I know. The next update for CR (which has been in the works for a while) replaces all my lang keys with versions with the modid, and localizes all the tooltips. See the 1.14 branch to see what I mean. 

Thermal expansion being able to use CR gears is working as intended (I added my gears to the ore dictionary for a reason :))

Thank you for your report.

**Comment by kappa-maintainer** [comment]
Thanks, one last question: Do 1.12 branch accept new translation? If not, I will translate on 1.14 branch only.

**Comment by Da-Technomancer** [comment]
1.14 only- 1.12 is unsupported at this point. 
Thank you for offering to do localization.
