### ISSUE TITLE
[Suggestion] Curios compat for leyden jar/beam cage

### ISSUE THREAD

**Issue by UvMidnight** [Da-Technomancer/Crossroads#107]
**Suggestion**
[Curios](https://www.curseforge.com/minecraft/mc-mods/curios), is the new mod that replaces baubles, and it exists. Compat for leyden jar/beam cage.

**Justification**
Been discussed before, only a matter of implementation.

**Comment by Da-Technomancer** [comment]
Added in the latest beta.
