### ISSUE TITLE
Crossroads machine recipes showing up as craftable in the vanilla crafting table recipe book

### ISSUE THREAD

**Issue by azaquaz** [Da-Technomancer/Crossroads#111]
Recipes which only work in Crossroads machines nonetheless appear as "craftable" in the vanilla recipe book for crafting recipes. For example, when you have iron ore in your inventory and select "showing craftable," iron grit, iron clumps, slag, and iron dust will all appear, despite being impossible to craft. Contrast with furnace recipes in vanilla, which appear in the recipe book only when the furnace GUI is open.

**Comment by Da-Technomancer** [comment]
As of testing in MC1.16.5 (and possibly several older versions), this issue no longer exists.
