### ISSUE TITLE
Smelting raw grits and clumps give incorrect amount of nuggets

### ISSUE THREAD

**Issue by TheLMiffy1111** [Da-Technomancer/Crossroads#113]
Smelting raw grits and clumps give 1 nugget instead of 6 nuggets.

**Comment by Da-Technomancer** [comment]
This is a known issue, but thank you for your report regardless.

Until this is fixed, I would suggest processing your grits/clumps in a blast furnace to result in x3 yields, instead of the x2 yields if this bug didn't exist, or x1/3 yields with this bug.

**Comment by TheLMiffy1111** [comment]
```
{
	"type": "minecraft:smelting",
	"result": "crossroads:nugget_copper",
	"count": 6,
	"experience": 0.7,
	"ingredient": [
		{
			"type": "forge:nbt",
			"item": "crossroads:ore_gravel",
			"nbt": {
				"material": "copper"
			}
		}
	]
}
```

**Comment by TheLMiffy1111** [comment]
FYI, Forge adds a feature to use a json object instead of a string to specify the result of smelting recipes, making it possible to specify outputs with a stack size larger than one. The syntax is the same as crafting recipe outputs.

**Comment by Da-Technomancer** [comment]
I would not have noticed that, thank you!
