### ISSUE TITLE
Multiplayer Gear Speed Desync

### ISSUE THREAD

**Issue by Varen** [Da-Technomancer/Crossroads#114]
**Describe the bug**
In multiplayer (listen server), as the client, rapidly switching gear systems seem to stop moving, but for the hosting player they work just fine.

**To Reproduce**
Created a windmill with an auto switching system when the wind changes direction, connected to a few heavy gears, and connected on the other side to a centrifuge with another gear switching. 

After a while, I keep hearing the clicking of the centrifuge, but the gears don't move anymore. 

If I check the gear speeds, even when they're still over 20 rot. They don't animate. Asking the host, he sees them move just fine.

**Comment by Da-Technomancer** [comment]
Could you please provide a picture of the exact setup causing this issue? 
A test setup matching what you described didn't display this issue.

**Comment by Da-Technomancer** [comment]
Closing the issue for inactivity as it's not been reproduced.
