### ISSUE TITLE
[1.16.1]Problem with Technomancy Path

### ISSUE THREAD

**Issue by Rumaruka** [Da-Technomancer/Crossroads#116]
Maybe I'm stupid, but I don`t unlock path, used Bronze gear.
Sorry if the question is stupid. Before asking it, I read the guide, watch your tutorial on YouTube, looked in project source code
![image](https://user-images.githubusercontent.com/8148679/91411668-167dbe80-e862-11ea-8e87-a69d97410816.png)

**Comment by Da-Technomancer** [comment]
Hi! Those video tutorials are for Crossroads 1, and are now invalid. 
In Crossroads 2 (the MC1.16 version), you unlock technomancy with 1 gear in the middle, and surrounding it in 8 of any gem (lapis works). Alchemy is unlocked with an empty bottle and 8 gems. Unlocking any path requires having discovered every alignment other than void.

I'd suggest relying on the ingame guide book over the video tutorials, as the guide book is up to date.
