### ISSUE TITLE
Reagent JEI integration doesn't work in multiplayer

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#119]
**Describe the bug**
When in Multiplayer, the reagent info JEI recipe category doesn't allow opening the recipe via looking at uses/sources of the item.

**Comment by mcadventurecity** [comment]
This seems to cause a crash in Singleplayer (1.16.3) as well... https://pastebin.com/585YzQ4Z

**Comment by Gbergz** [comment]
Hey,
Any idea when you're releasing an update fixing the crash @mcadventurecity mentioned?

**Comment by Da-Technomancer** [comment]
@Gbergz The latest update fixes that crash.

**Comment by Gbergz** [comment]
It's not on CurseForge though is it?

**Comment by Gbergz** [comment]
Nevermind just got released.

**Comment by Gbergz** [comment]
Seems to still crash with the new update, unfortunately.

This file specifically: https://www.curseforge.com/minecraft/mc-mods/crossroads-mc/files/3076387

**Comment by Gbergz** [comment]
Latest crash, https://gist.github.com/Gbergz/4913dacdead55e6dd1752c0c151209a7

**Comment by Da-Technomancer** [comment]
@Gbergz please use this specific file; even though it has the same name/number on the Curseforge page, it is a different file.
The previous version was uploaded twice by mistake; this has now been corrected. 

https://www.curseforge.com/minecraft/mc-mods/crossroads-mc/files/3077633

**Comment by Gbergz** [comment]
Can confirm the crash I mentioned is fixed now. Thanks!
