### ISSUE TITLE
missing tags

### ISSUE THREAD

**Issue by TheNimbleNinja** [Da-Technomancer/Crossroads#120]
your missing tags from items in 1.16.2 and its refusing to create worlds cause of this

**Comment by Da-Technomancer** [comment]
I need some actual information- world creation works fine under normal conditions.

Logs? Actual messages? How were you trying to make a world that failed? Which Crossroads version are you using? Where are you getting 'missing tags from items' from?

**Comment by Da-Technomancer** [comment]
I'm closing this because there was so little information given, I can't even tell if they actually experienced a bug. I've also not reproduced any bug meeting this description.
