### ISSUE TITLE
Server crash when pushing Water Centrifuge with vanilla sticky piston

### ISSUE THREAD

**Issue by jayschuster** [Da-Technomancer/Crossroads#123]
**Describe the bug**
Crash when pushing Water Centrifuge (nothing inside it, no rotational power) with vanilla sticky piston

**To Reproduce [Optional]**
1. Place water centrifuge
2. Place sticky piston pointing at it
3. Power sticky piston with lever
4. Server crash

**Expected behavior [Optional]**
Either the block not to move, or the block to move

**Additional context [Optional]**
Crash log: https://pastebin.com/J0APTTyi

**Comment by Da-Technomancer** [comment]
This bug only occurs when Quark is installed, as without Quark tile entities can't be pushed with pistons. Flagging this as an incompatibility.
