### ISSUE TITLE
Stirling Engine bug

### ISSUE THREAD

**Issue by StrangerSon712** [Da-Technomancer/Crossroads#124]
My Stirling Engine is getting heated on the side by the heat setup for the bottom, despite no cable connection.

**Comment by Da-Technomancer** [comment]
The Stirling engine moves heat between the side and bottom inputs when generating power; not only do you have to heat the bottom, but you also need to keep the side cool (all the heat you're putting into the bottom gets shared with the sides). Usually, connecting a simple Heat Sink to the sides is plenty to vent the heat.

**Comment by StrangerSon712** [comment]
So the only way to automate the stirling engine is automatic fuel or beams?

**Comment by Da-Technomancer** [comment]
There are many heat sources- not all of them are fuel or beam based (including solar and lava).
