### ISSUE TITLE
Comparator support for the Smelter

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#126]
**Suggestion**
It would be useful if Smelters would output a value indicating how many items are in the input slot

**Current Behavior [Optional]**
Currently, Smelters output a value of 0 always

**Justification**
It would be nice to be able to control an indicator (lamp or noteblock) for when a Smelter is done smelting stuff, but there is a possible balance concern (depending on how the heat system is supposed to be worked) of being able to automate when heat will be provided to a smelter, which makes heat systems much more efficient.

**Comment by Da-Technomancer** [comment]
I'm going to expand on this issue: A lot of machines should have comparator/circuit support.

- [x] Smelters for items in input
- [x] Millstone for items in input
- [x] Blast furnace for items in input
- [x] Stamp mill for either items in input, or accumulated progress
- [x] [Clockwork] Beam stabilizer for stored beam power
- [x] Tesla coil base for stored FE
- [x] Ore cleanser for items in input
- [x] Steamer for items in input
- [x] Ice/firebox for either burntime or items in input
- [x] Voltus generator for stored voltus
- [x] Contents/fullness of reaction vessel
