### ISSUE TITLE
Void-Time Beam, Stasis

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Crossroads#129]
Scope:
A new beam type, Stasis. Made by mixing a void beam with a time beam. A new Technomancy block for chunkloading that makes use of it, and a transmutation mechanic that allows for fully automated Adamant

Suggestion:
New beam type, Stasis, or void time
This beam, when above power 32 transmutes obsidian blocks into bedrock, but only if they are within 7 blocks vertically of y=0 in the overworld, and y=0 or y=128 in the nether, and does not transmute it in the end.
New late-game Technomancy block, the Stasis Field Generator. This block chunk loads a radius of chunks equal to floor(Stasis Beam Power/1000), with a limit of 3 chunks (3000 stasis beam power)
Justification:
I think that this adds to the existing mechanics in a meaningful way. It provides a use for ridiculously high power beacon harness setups, as well as providing a means to automate things that could not be renewably automated beforehand, as well as providing a means to PATCH HOLES IN BEDROCK, something which I believe the current version of the mod is missing.

Impact:
First and foremost, I think that both of these mechanics should be configurable, with the defaults being those stated above. Server owners should be able to control the y level for bedrock creation, and control if chunks can be loaded by players. Another issue is bedrock trapping, which is the reason I imposed the y level limitations. Players should simply avoid logging off or going afk at those y levels. This could easily be explained in the lore by saying that the bedrock ‘aura’ is the strongest at those levels.

For more info, contact @The-Minecraft-Scientist#7080 on Discord

**Comment by Da-Technomancer** [comment]
Adamant is already fully automatable- there's a positive return on adamant when making bedrock dust with adamant + alchemical salt, then dissolving the bedrock back into adamant. 
Also, even with the height restrictions and server configs, making bedrock blocks in the world is a big no-no- it doesn't matter how convoluted and hard it is, or how incredibly cleverly stupid you would have to be, but _someone_ will find a way to perma-trap themselves. 

The key suggestions here are: Change the effect of void-time beams and add a way to do chunkloading with technomancy.

**Comment by Da-Technomancer** [comment]
Closing this, as chunkloading with technomancy powered by time beams has been added since this issue was opened, and I like the current void-time effect.
