### ISSUE TITLE
Charm Acquisition wipes Heat Reservoirs

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#131]
**Describe the bug**
When breaking a heat reservoir with ~~silk touch~~ acquisition, a heat reservoir without a temperature is returned.

**Expected behavior [Optional]**
Really, just the normal drop would be fine.

**Comment by Da-Technomancer** [comment]
Issue also applies to fluid tanks and, presumably (untested), reagent storage vessels.

**Comment by DaedalusGame** [comment]
Probably related to https://github.com/svenhjol/CharmForge/issues/9

**Comment by Da-Technomancer** [comment]
Charm's Acquisition enchantment uses loottables directly without ever calling harvestBlock. Changing reservoirs/tanks/vessels to do the contents-keeping through the loottable like shulker boxes do would fix the issue.

**Comment by Da-Technomancer** [comment]
Just tested- this issue still exists even with Charm 2.3.1 claiming to fix these issues.
