### ISSUE TITLE
Maximum temperature doesn't match displayed maximum temperature

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#132]
**Describe the bug**
Smelters (and probably others too) display 32767°C as the maximum value, but actually store 50000°C according to the omnimeter.

**Expected behavior [Optional]**
Smelters should display values past 32k

**Comment by Da-Technomancer** [comment]
Heat machines use container int reference packets to track temperature for the UI. This caps the value at the maximum short value.
This could be fixed by either using multiple references and combining them, or by switching to a separate container packet system.

**Comment by Da-Technomancer** [comment]
Closing this, as it's a wontfix issue that's purely visual and related to a maximum displayed value in a UI.
