### ISSUE TITLE
Water Centrifuge Crashes Serverside When Processing Empty Tank

### ISSUE THREAD

**Issue by MushroomDynamo** [Da-Technomancer/Crossroads#138]
**Describe the bug**
Attaching a gear to a network that's already oscillating back and forth every 3 redstone ticks such that it would activate an empty water centrifuge (which already has a fluid tube and gold hopper pulling out of it) crashes with an empty stack modification issue.

**To Reproduce**
NOTE: NOT SURE IF THIS REPRODUCES.
1. Multiplayer presumably, can't reproduce in singleplayer
2. Acquire water centrifuge, possibly multiple?
3. Attach gold hopper to pull items out and fluid tube extract fluid
4. Set up gear network to oscillate between 0.5 and -0.5 rad/sec every 3 redstone ticks
5. Attach gear to top of water centrifuge
6. [crash-2021-01-24_21.41.27-server.txt](https://github.com/Da-Technomancer/Crossroads/files/5863942/crash-2021-01-24_21.41.27-server.txt)

**Expected behavior**
Water centrifuge does not cause world corruption via ticking entity crash loop.

**Comment by Da-Technomancer** [comment]
Unclear what would have led to the invalid recipe to cause this specific issue, but it won't crash in the future.
