### ISSUE TITLE
(Inverted) Toggle Gear sound not directional clientside

### ISSUE THREAD

**Issue by Varen** [Da-Technomancer/Crossroads#146]
**Describe the bug**
The sound of a toggle gear being toggled, on a client, isn't coming from the gear but from "everywhere", as if it was centered on the player, all the way up until a distance, where the sound disappears completely.
Tested on a LAN server, the host doesn't have this issue.

**To Reproduce [Optional]**
A setup with a toggle gear and an inverted toggle in the same block used to switch the direction of a centrifuge will have this issue.

**Comment by Da-Technomancer** [comment]
I've tested this, and it's working fine for me.

However, issue #149 also reports issues with the sound from toggle gears (a different issue, but still), and I can't reproduce that one either.

Either there is something _very_ intermittent with the toggle gear sounds, or there's something about the sound that makes people think they can't hear it properly.

**Comment by Da-Technomancer** [comment]
Closing the issue for inactivity as it's not been reproduced.
