### ISSUE TITLE
Changing Beam Transmutation Recipes via DataPack Causes JEI to not Function in Multiplayer

### ISSUE THREAD

**Issue by Crazydude323** [Da-Technomancer/Crossroads#147]
**Describe the bug**
When you use a DataPack to edit Beam Transmutation recipes, it causes JEI to not function in multiplayer.

**To Reproduce [Optional]**
1. Install [this datapack](https://github.com/Da-Technomancer/Crossroads/files/6631325/Crossroads-Changes.zip) on a server.
2. Boot up Minecraft, and join the server.
3. Try to view the recipes for various items.
4. JEI does not function.

**Expected behavior [Optional]**
For the DataPack to edit the recipes successfully, and JEI to function properly.

**Additional context [Optional]**
I originally had an issue for this on JEI's repository [(here)](https://github.com/mezz/JustEnoughItems/issues/2384#issuecomment-858564231) because I didn't know exactly what was causing it to stop functioning. After numerous days of testing, I've discovered the aforementioned DataPack I made to be the culprit. It was only intended to edit the power required for a beam to transmute rock to glowstone or redstone, as well as to disable the Sea Lantern transmutation (there is a bit of leftover editing from when I tried just changing the block required). It functions perfectly fine in single player, but on a server, it causes JEI to not function.

**Comment by Da-Technomancer** [comment]
This issue should be fixed with Crossroads 2.6.5. 
If updating doesn't fix the error, please re-open this issue.
