### ISSUE TITLE
beams and toggle gears are not affected by block volume

### ISSUE THREAD

**Issue by stevehello166** [Da-Technomancer/Crossroads#149]
beams and toggle gears are not affected by block volume this is not a major issue I just  wanted to point it out

**Comment by Da-Technomancer** [comment]
What Crossroads version are you on?

**Comment by stevehello166** [comment]
the version is
2.26.5

**Comment by Da-Technomancer** [comment]
There is no Crossroads 2.26.5. Do you mean 2.6.5?

I've just tested this, and both toggle gear and beam sounds are adjusting with my block volume for me.

**Comment by stevehello166** [comment]
must be an issue on my side i will look into it

**Comment by Da-Technomancer** [comment]
Closing the issue for inactivity as it's not been reproduced.
