### ISSUE TITLE
Add Anti-Densus to Maxwell’s Demon recipe [SPOILERS]

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Crossroads#153]
Suggestion:
Self explanatory 

Current Behavior:
Recipe is bedrock dust, fat blobs and copper
Justification:
I won’t pretend that bobo items should be balanced, but I will say that the Demon currently takes a LOT of effort and thought out of alchemy
Pretty much every reaction can be boiled down to “slap Demon, slap regulators, pipe in ingredients, profit” This would at least require you to progress through alchemy further before unlocking such a powerful tool, as well as being more accurate to the real Maxwell’s demon, which requires the door separating the two chambers of gas to be massless, or the Second Law still applies (it takes work to move the door)

**Comment by Da-Technomancer** [comment]
Added in 36996efbc89cd1770f728ddb6cb0aca49cebaf63
