### ISSUE TITLE
drill being hit by an energy beam

### ISSUE THREAD

**Issue by koostcrashed** [Da-Technomancer/Crossroads#156]
**Describe the bug**
a crash happened when i timed a charge beam at a (i think) breaking block (by drill). 

**Additional context [Optional]**
https://pastebin.com/YhimEM9i
The actual crash log.

**Comment by koostcrashed** [comment]
as requested
the beam siphon was targeted at a cobblestone generator. it hit the cobblestone with a charge beam. then it is broken by a drill. it has hit the drill before without crashing.

**Comment by koostcrashed** [comment]
some testing later

It is the drill (not turning facing towards the beam) being hit by an energy beam.
-the wind turbine also crashes when hit by an energy beam

**Comment by Da-Technomancer** [comment]
Fixed in commit 34dc8e1f8d8053679fff9bf96f15bce18cdccc1d
