### ISSUE TITLE
[1.16.5] DATAPACK LOAD ERROR with Dimensional Ores

### ISSUE THREAD

**Issue by Cynix32** [Da-Technomancer/Crossroads#165]
**Describe the bug**
A datapack load error on world loading with crossroads (and its dependencies) and DimOres installed. Tested with only those mods, error still occurs. This was isolated from my fairly large private modpack after adding crossroads into it.

**To Reproduce [Optional]**
Download these files from curseforge:
crossroads-1.16.5-2.6.5.jar
Dimensional_Ores-1.16.5-1.0.0.8.jar
essentials-1.16.5-2.11.1.jar (dependency of crossroads
Patchouli-1.16.4-53.2.jar (dependency of crossroads)
Load an existing world or make a new one, then reload it
You'd then be greeted with the datapack load error screen

**Expected behavior [Optional]**
Obviously to not have an error and load the world

**Screenshots [Optional]**

**Additional context [Optional]**
Referencing AlgorithmLX-Team/DimOre#5
log from console:https://pastebin.com/hL3456qL

**Comment by Da-Technomancer** [comment]
Issue seems to be resolved in newer MC versions, and the older MC versions are unsupported for Crossroads.
