### ISSUE TITLE
Jump to block in guide book

### ISSUE THREAD

**Issue by Rushmore75** [Da-Technomancer/Crossroads#168]
**Suggestion**
Have it so when you hold the guide book and shift right click (or similar action) it jumps right to the page of the block you click on

**Justification**
This would make the creation on machines faster if you - say - forget what side a heat duct goes on, or where the rotary power i/o is on a block. Or, with such items as the stamp mill, make sure you have the right rpms going into the machine. I have seen this idea in mods such as pixlemon and in-game-wiki, where you hit a key-bind and it jumps you to the page in documentation.

Another alternative would be to add it to jei such as Actually Addons does. On every item you can read the book right from jei, creating a similar result as the first implementation.

**Comment by Dilnu** [comment]
This could be accomplished either by adding recipe pages to the book or using "extra_recipe_mappings" see [the bottom of the entry docs page.](https://vazkiimods.github.io/Patchouli/docs/reference/entry-json/)

**Comment by MrDrProfNo** [comment]
I am working through what items should open which entries. My go-to is that the entry's icon will be used as a link to the page, unless in my own personal opinion its use is wider ranging than the page (vanilla items, for the most part) or there's a better place for it to be linking (glass shells will link to Glassware, not Reagent Effects).

It will take me several days to work through all the entries and think about this. While these are obviously gonna be open to change later, _now_ would be a convenient time for any suggestions outside of the above.

Multiple items can go to the same entry (and specific pages within the entry) but the same item cannot go to multiple entries.

**Comment by Rushmore75** [comment]
I think that makes sense: just have each item/block link to the most relevant part of the book.

👍
