### ISSUE TITLE
Detailed Crafting bugs

### ISSUE THREAD

**Issue by anom3** [Da-Technomancer/Crossroads#173]
**Describe the bug**
There is no JEI integration with the Detailed Auto-Crafter and multi-path recipes require a specific path in the Detailed Auto-Crafter.

**To Reproduce [Optional]**
1. Open Detailed Auto-Crafter GUI
2. Open JEI tab for Detailed Crafting
3. See that there is no plus.
4. Insert Detailed Crafting recipe for Detailed Crafter
5. See that you need a specific sigil (witchcraft for me)

**Expected behavior**
3. There is a plus.
5. Any sigil works.

**Comment by Da-Technomancer** [comment]
Which recipe were you trying that it required witchcraft and you expected something else?

**Comment by anom3** [comment]
Actually I think you misunderstood. With the Detailed Auto-Crafter SPECIFICALLY, it required witchcraft to make Detailed Crafters with the cheap recipe. I expected it to work with any path.

**Comment by anom3** [comment]
It works with any path on the manual Detailed Crafter.

**Comment by anom3** [comment]
(I think) I can test

**Comment by anom3** [comment]
aaand yup it works with any path manually.

**Comment by anom3** [comment]
the recipe
![image](https://user-images.githubusercontent.com/97539748/149201131-6a2aee42-723d-4c74-a339-985cb8c68889.png)

**Comment by anom3** [comment]
I think there is a relatively easy way to fix the auto specific sigil requirement. Making multi path recipes (recipes that are allowed in multiple paths) one recipe internally that specifies multiple allowed paths should work.

**Comment by Da-Technomancer** [comment]
Created a new issue in the process of fixing this: #174
