### ISSUE TITLE
Crash upon something killing plants.

### ISSUE THREAD

**Issue by anom3** [Da-Technomancer/Crossroads#175]
**Describe the bug**
Once something attempts to kill plants (even if there are no plants in range) the game crashes.
How doesn't matter. You could use: A cubic metre of salt (salt block), a not-actually-magic dark green laser (void-potential beam's effect) or a laboratory "accident" (releasing salt reagent).

**To Reproduce**
1. Place salt block
2. Crash
3. Fire void-potential beam
4. Crash
5. Release salt reagent
6. Crash

**Expected behavior**
Not a crash!

**Additional context**
Crash Logs:
Salt Block https://pastebin.com/dx5bkRX0
Void-Potential https://pastebin.com/TxEirCyi
Salt Reagent https://pastebin.com/Yt47Eej1

**Comment by Da-Technomancer** [comment]
Fixed in latest version. Thank you for the report.
