### ISSUE TITLE
Path Sigils aren't giving the advancement.

### ISSUE THREAD

**Issue by Dilnu** [Da-Technomancer/Crossroads#176]
**Describe the bug**
Right-clicking a path sigil when you don't have the path advancement doesn't grant the advancement to you.
Note I tried this in 1.18.1-2.7.2 I then tested the detailed crafter method for getting the advancement and that did work.

**Comment by Da-Technomancer** [comment]
Were you right clicking on a block, or in the air? In testing, it works fine when clicking on a block, but doesn't respond it clicking in the air.

**Comment by Da-Technomancer** [comment]
Closing this issue, as the reporter hasn't answered back whether the applied changes were effective at fixing their issue, and no similar issue has been reported since the changes.
