### ISSUE TITLE
Log spam on startup 'unknown recipe category'

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#180]
**Describe the bug**
When joining a world, several entries are logged along the lines of '[Render thread/WARN]: Unknown recipe category: crossroads:formulation_vat/crossroads:formulation_vat/nutrient_solution_alchemic', but for every Crossroads machine recipe. 

It causes no other issues, other than the log spam.

**Comment by Dilnu** [comment]
Note this also happens on every /reload
