### ISSUE TITLE
Tooltips broken for Alchemy in latest JEI

### ISSUE THREAD

**Issue by Dilnu** [Da-Technomancer/Crossroads#181]
**Describe the bug**
Tooltips broken for Alchemy in latest JEI

**Additional context [Optional]**
[Latest.log](https://gist.github.com/Dilnu/3f1e721d6a716b310488ec89f577c646)

**Comment by Da-Technomancer** [comment]
Was fixed in b8aacc3722b787aa1c19ed0a70e0a6d94b6c6698
