### ISSUE TITLE
Reaction chamber temperature below absolute zero

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#182]
**Describe the bug**
It's possible to get the reaction chamber below absolute zero.
Not clear how this originally occurred; temperature got more negative when an item shifter attempted to add redstone to a full reaction chamber, which didn't move any items or reagents but lowered the temperature. 

NBT printout from the reaction chamber: "[CHAT] -401, -56, -277 has the following block data: {glass: 0b, temp: -19695.06374944871d, qty_sulfur_dioxide: 86, x: -401, qty_aether: 116, ener: 0, y: -56, initHeat: 1b, z: -277, id: "crossroads:reaction_chamber", he: -3923256.8773886394d}"

**Comment by Dilnu** [comment]
Probably related:
[CHAT] -402, -56, -277 has the following block data: {inv: {id: "minecraft:redstone", Count: -56b}, x: -402, y: -56, z: -277, id: "essentials:item_shifter"}
