### ISSUE TITLE
Server Crash with JAOPCA

### ISSUE THREAD

**Issue by evhub** [Da-Technomancer/Crossroads#185]
**Describe the bug**

Server crashes when loading with Crossroads and JAOPCA—removing either mod resolves the crash. I previously reported this issue to JAOPCA (https://github.com/TheLMiffy1111/JAOPCA/issues/224) and the JAOPCA author indicated that it was likely due to an issue with how Crossroads parses fluid ingredients.

**Crash report**

https://gist.github.com/evhub/6204b42e3fb3665e42a7773a869289dc

**Versions**

Minecraft 1.18.1, Forge 39.0.75, and Crossroads 2.7.2.

**Comment by KatoNamus** [comment]
Getting same issue

**Comment by Da-Technomancer** [comment]
@KatoNamus Please post your crash log or debug log.

**Comment by KatoNamus** [comment]
Crash log [here](https://pastebin.com/F58PhHhF). Let me know if you need anything else. I'm not playing that particular modpack anymore and can use that to test ideas/fixes for you.

**Comment by Da-Technomancer** [comment]
The way tags work gets totally changed in MC1.18.2 vs MC1.18.1. Delaying fixing this until MC1.18.2, especially as there is basically no tag documentation in 1.18.1, unlike in 1.18.2.
