### ISSUE TITLE
Witchcraft Hemic Entanglement Chamber

### ISSUE THREAD

**Issue by CvoidWyvern** [Da-Technomancer/Crossroads#203]
**Scope**
New Witchcraft machine with beam-dependent mechanics, similar to Crystalline Master Axis. Creates a magic connection to an entity using blood.

**Suggestion**
Machine that can be used to affect the entity/player that it has the blood of over any distance/across dimensions, with each beam alignment having a different effect. Inspired by the Various Oddities Disembodied Heart and Incorporeal Blood Soul Core. Thematically would be similar to the Blood Compas, and probably would use one in the crafting recipe. Changing the alignment used also changes what the circuit reader reads from the block.

Would of course not work with spoiled blood, and also would not work if hit by 2 beams at once, unless at least one of those beams is fusion. Only one Hemic Entanglement Device could affect an entity at a time, interfering with each other if two are connected to the same entity. Due to loss of blood, effects stop working when on very low health.

Functionality per beam alignment as follows:

- Enchantment: Applies potions from the buffer, similar to the auto-injector. Circuit reader gets potion effect count.
- Rift: Items inserted into the HEC are inserted into entity's inventory, prioritizing armor slots (and held item if not a player). Circuit reader gets # empty inventory slots.
- Charge: Charges items in entity inventory using FE. Circuit reader gets total empty FE between all items.
- Light: Places lights at entity location when given redstone/circuit signal. Circuit reader gets light level at entity location.
- Potential: Applies the effect of nearby Fat Feeders to the entity, circuit reader gets current hunger for players, and breedability status for animals. (healing would be redundant with Enchantment)
- Time: Applies any temporal effects that would be affecting the HEC to the area around the entity. Circuit reader gets the current acceleration around that entity, including this effect.
- Energy: When the entity would take fire damage, instead increase machine heat, and vice versa with cold damage. If the machine's heat is too high or too low, instead deals damage to the player to reduce/increase the heat. Circuit reader gets block temperature.
- Fusion: Allows a second beam to be used to charge any beam cages in inventory. Cannot send void. Circuit reader gets total beam cage power, excluding void.
- Stability: Gives explosion immunity (assuming that stability becomes this) Either this, Equilibrium, or Expansion would make the circuit reader output based on a specific item made for use with this machine, and also display current beam color/alignment (and maybe a rotary input), similar to how the old Technomancy prototype items would have simple IO that you'd have to make mean something.
- Expansion: Extra block reach based on rotary power (high I value and diminishing returns)
- Equilibrium: ??? (something with what Equilibrium becomes)
- Void or void involved beams: Chance to destroy blood sample.

(considered maybe combining the Enchantment effect into Potential by allowing it to use auto-injectors as well, then moving the Fusion effect to enchantment, and adding an Alchemy focused effect to Fusion so both Technomancy and Alchemy have an effect on there, but couldn't think of a good Alchemy effect)

**Justification**
- Adding a powerful Witchcraft machine where the player can choose how much of an automation puzzle it is. You can choose to only set it up for one effect for yourself to make it not much of an automation puzzle, but that would lock you out of all the other effects.
- Adding a versatile machine that can be used to help the player, read data about the player, read data about farm animals, buff allied mobs, and much more, widening what Witchery can do while still sticking to the niche of entity manipulation.
- Adding another use for blood, as well as adding more uses for many other mechanics.
- Having some toys for all the people who hear 'Witchcraft' and think 'Witchery' and want to 'do a little trolling' on servers, without it being *too* toxic.

**Impact**
This would add another powerful tool to Witchcraft , but keeps in line with the idea of Witchcraft mostly just doing stuff that affects entities and plants. This makes the Witchcraft path even better for the type of player who isn't really interested in automation and probably wouldn't enjoy Alchemy/wouldn't be making many things that would benefit from Technomancy. It would probably have to require previous Witchcraft items/be later in progression, as many of the effects are quite powerful out of the box.

'Doing something with blood that affects who that blood belongs to' fits the theme of Witchcraft

The HEC would overlap a bit into the auto-injector's use cases, but due to the fact that this requires blood the auto-injector is usually the better choice where they overlap.

We realize this is a *very* big idea/complicated machine. Only implementing some at a time and leaving some alignments missing for later would work fine, or just implementing one or two alignments here as their own machines and leaving out the rest. This is more inspiration/putting down ideas than a direct suggestion.

**Comment by Da-Technomancer** [comment]
There are some very solid suggestions in here, but as you correctly noted this machine is _nightmarishly_ complicated.
All together, there would be: 2 beam inputs, an item input, an item output, a blood-specific item input/output, FE input, heat input/output, conditional circuit reading, redstone input, rotary input. Also, interaction with technomancy time acceleration field and fat feeder AOE. 

It needs some heavy simplification. 
As an example (not saying this is the answer): suppose if all it did was 'target beam effect at entity from anywhere'. 
That gives 'wireless' explosion protection, healing, and killing.
If some beams got new entity-targeting effects (see #214), that would get several more of your suggestions into the mix.

**Comment by CvoidWyvern** [comment]
That's a solid way of simplifying it, especially if either something about the machine or a change with #214 would make continuous healing less effective. The fat feeder part was just from thinking about how broken potential could be (+ redundancy with enchant) and trying to think of a different effect that would fit potential without trivializing a bunch of other content. 

Think that with a simplified machine it's important to still keep it one per player, so players have to either choose one positive effect to have at a time, or set up a machine to switch the effects based on some logic. Down the line it would be nice to have some way of reading information about the player to use alongside a machine like this but it isn't necessary to do some interesting automation around it, and while having it be the same machine adds more challenge, it's still interesting without that. Could even maybe make some sort of flight with it if the beam can be input from any side and there's something to remotely communicate with your automation.

Alternative simplification idea: it could cause the player to be affected by any 'fields' it's inside of, as if the player was at the position of the machine (auto-injector, fat feeder, temporal accelerator, maybe vanilla beacons, etc). Could do this with a machine, or the machine could be a way to hold and maintain an entity that syncs potion effects, health, hunger, etc with the player to both give it more of a witchcraft vibe and allow more emergent gameplay with other mods. Maybe part of the entity is the result of trying to clone a player? Could still do that thematically without the entity, just with an item. Could have both simplification ideas via having a machine that applies a beam effect as a field, like an entity only temporal accelerator for all beam types. TBH that could be neat by itself without any of the rest of this as a feature to go alongside #214. Very much still just rambling out ideas, hope at least some of these are useful.
