### ISSUE TITLE
Friction Heater

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Crossroads#204]
**Scope**
New rotary machine

**suggestion**
Friction heater, a gear that generates heat in adjacent heat reservoirs when powered by redstone, converting rotary power to heat (at the same exchange rate offered by steam engines)

**Justification**
feature completeness, and having a handy way to generate a bit of heat 

**Impact**
minimal. most rotary setups use heat anyways, so it wouldnt be much more than a utility item.

Similarly to the toggle gear, it should stick out contacts or something that rub the heat reservoir when activated

**Comment by Spontaneo** [comment]
Impact addition
Increases cross mod compatibility if combined with the lode stone to turn FE into rotation

Mechanic
Have a sweet spot for rpm/heat gen as being to slow won't generate heat and to fast will melt/ break the friction gear
