### ISSUE TITLE
Hand crank spam-clicking

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#205]
**Describe the bug**
The hand crank, which is supposed to provide power at a constant rate while held down, will provide an impulse of energy when first clicked, then repeating every few ticks thereafter. This is vulnerable to spam-clicking and autoclickers, as each initial click creates a new initial impulse of energy, enabling far higher effective power production rates than intended.

Can be fixed by not providing the first impulse on the initial click or delaying it.

**Comment by Random-Scientist** [comment]
This is fixed by #217
