### ISSUE TITLE
Gmae crashes when you respawn in the overworld within range of a blood centrifuge

### ISSUE THREAD

**Issue by Random-Scientist** [Da-Technomancer/Crossroads#206]
**Describe the bug**
Game crashes on a nullpointer exception related to the blood centrifuge model
https://mclo.gs/iUgDa4U

**Comment by Da-Technomancer** [comment]
This was fixed in 653e31ed81f077b29d1c238073c7231d06dd0c50, but the update hasn't been pushed yet.
