### ISSUE TITLE
Alchemy Gravity/Force Machine

### ISSUE THREAD

**Issue by CvoidWyvern** [Da-Technomancer/Crossroads#207]
Collecting ideas from this discord discussion and adding onto it, credit to the others involved here
https://ptb.discord.com/channels/350295689789440000/350295690246881288/976565002024665139

**Scope**
New Alchemy machine or generic machine that can be pushed further with Alchemy items, to complement 'new' beam type.

**Suggestion**
Machine that applies a force in an area with radius dependent on beam power, and direction + magnitude dependent on input force beam power, temperature, and block orientation, counting disruption as negative. Something along the lines of beamPower * (n - temperature), n being relatively close to ambient temperatures. 

The machine temperature changes for each entity affected (discount on items), with the amount based on distance. While in the area, holding shift clamps the force between being low enough to fall, high enough to jump one block (or half a block), and negates x and z force, similar to how other gravity related blocks allow escaping them by holding shift. Another item could be crafted to allow overriding this, with shift adding a downwards force and space adding an upwards force. Machine can be rotated on its side. (maybe also allow direction skewing using two optional gear inputs)

With the beam power and temperature regulated perfectly this + an item to increase or decrease self gravity slightly gives creative flight in an area. On its side it can become a minecart/boat booster, one way mob gate, arrow accelerator, etc.

If not an alchemy machine by default, would have its radius or max radius multiplied drastically by giving it a supply of densus.

**Justification**
Alchemy feels kinda lacking compared to the others, especially since the benefits of alchemy either overlap a lot more with what other mods allow or are more niche compared to technomancy and wichcraft. Time acceleration is always useful and rarely added for both blocks and entities by other popular mods, and similar can be said for arbitrary infinite potion effects. For alchemy there's resource generation which is a relatively common feature in one way or another and biome changing which is uncommon but not as useful as acceleration or infinite effects. The gravity related items in alchemy are an interesting start that has a lot of potential.

**Impact**
Adds more reason to focus on alchemy instead of the other two, and a balanced method of flight. May replace using multipiston retraction + slimeblocks to accelerate players/mobs in some cases.
Once more space mods get updated this could work interestingly with them as well.

**Comment by Da-Technomancer** [comment]
With the newly-added Blood Effigy, something similar to this is now possible with Witchcraft, using force beams on a blood effigy linked to the target entity/player. While the effigy method only affects one entity at a time, area-of-effect stuff can be done with gravity plates.
