### ISSUE TITLE
[1.16.5] Server crash on startup with Infernal Expansion

### ISSUE THREAD

**Issue by Diversion98** [Da-Technomancer/Crossroads#209]
**Describe the bug**
The server crashes when I start a fresh new server.
On a client, the mods works just fine.

When I delete Crossroads 2.6.5 from the server and keep Essentials 2.11.1, the server starts just fine.
When I infernal-expansion 2.4.0 and keep Crossroads and Essentials, the server starts just fine.

**To Reproduce [Optional]**
1. add the folowing mods to a minecraft forge 36.2.35 server:
    - Crossroads 2.6.5
    - Essentials 2.11.1
    - Infernal Expansion 2.4.0
    
2. Start the server and watch it fail
3. Delete Crossroads or Infernal Expansion
4. Start the server and watch it succeed

**Expected behavior [Optional]**
compatibility between the 2 mods so it can start on a server (client works just fine)

I also made an issue on their github: https://github.com/infernalstudios/Infernal-Expansion/issues/366

[latest.log](https://github.com/Crossroads-Development/Crossroads/files/9034235/latest.log)
[debug.log](https://github.com/Crossroads-Development/Crossroads/files/9034236/debug.log)

**Comment by Dariensg** [comment]
Apologies for the issue, but the user is using an outdated version of Infernal Expansion. The issue should be fixed in the latest version of Infernal Expansion!

**Comment by Da-Technomancer** [comment]
@Dariensg thank you for the heads up!
