### ISSUE TITLE
Crashing upon placing Block

### ISSUE THREAD

**Issue by CTH999** [Da-Technomancer/Crossroads#225]
**Describe the bug**
Placing the Creative Resonance Extractor, or the regular resonance Extractor, gear, diorite...

**To Reproduce [Optional]**
1.Place resonance extractor
2. See error

**Expected behavior **
Not crashing

Additional context
I have all required mods+JEI (and Configured for the second test).
exit code of "-1"

Without "configured"
[crash-2022-09-08_09.16.35-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9527599/crash-2022-09-08_09.16.35-client.txt)

With "configured"
[crash-2022-09-08_09.19.31-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9527608/crash-2022-09-08_09.19.31-client.txt)

With regular extractor: 
[crash-2022-09-08_09.44.11-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9527849/crash-2022-09-08_09.44.11-client.txt)

Beam Reflector: 
[crash-2022-09-08_09.45.51-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9527866/crash-2022-09-08_09.45.51-client.txt)

Gear: 
[crash-2022-09-08_09.47.58-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9527888/crash-2022-09-08_09.47.58-client.txt)

Diorite:
[crash-2022-09-08_10.22.08-client.txt](https://github.com/Crossroads-Development/Crossroads/files/9528186/crash-2022-09-08_10.22.08-client.txt)

**Comment by Da-Technomancer** [comment]
The issue is due to an incompatibility between your Forge version (41.1.0) and your Patchouli version (1.19-74).

See:
![image](https://user-images.githubusercontent.com/11035641/189162664-b28374e0-d78b-4a10-906c-e7bedc74a8e8.png)


Closed because this is not a Crossroads bug.

**Comment by CTH999** [comment]
thanks!
