### ISSUE TITLE
Witchcraft Improvments

### ISSUE THREAD

**Issue by CTH999** [Da-Technomancer/Crossroads#227]
**Scope**
It's a good quantity of additions to witchcraft

**Suggestion**
1. Other Items in clones: other items, such as netherite, can improve them with more armor, health, or more!
2. "Steryotypical" witcraft
   1. Special Potions (seems most cross-roadsy and easy (ish) to implement
   2. Broomsticks and other magical tools (maybe)
   3. Spells. Not sure how to make it unique to other mods spells, nor how to make it "crossroads-y", so... unliky, but a 
   4.   thought all the same.
5. Ability to make mobs hostile to only a specific player/ ignore groups of players (or even protect them). _But_, it won't drop items to players that it's no hostile to! (If it's a naturally hostile mob)

There are also some unlikely ones. One can dream though, right?
6. The ability to clone yourself to make a being that can be controlled and do player-actions. Doesn't move without your interaction, and defaults to being able to be controlled
7. Enchanting Clones: Enchantments can have special effects on clones, or just do their normal effects.
8. Synthetic Creatures (My favorite): Allows createing custom creatures (to an extent with their looks), that can be programed to do certain things, just controlled, or given tasks! These are probally too complex, _but_ one can dream, one can dream...

A doc with more info (Though not necessary info) is [Here](https://docs.google.com/document/d/1kwfrWOq3ejH6Ekbupd_WQxiH0UOlDFo6/edit?usp=sharing&ouid=118013032969542638389&rtpof=true&sd=true)
A discussion I started on it is [Here](https://discord.com/channels/350295689789440000/1018592214265376879)

**Justification**
Simple. It will add _a whole lot_ more to witchcraft, allow it to protect those in hardcore, at a cost. Allow you to weaponize sheep and such, and more!

**Comment by Da-Technomancer** [comment]
Suggestion 1 is written up in #277. 
Suggestion 3 is written up in #253.
The rest are out of scope for now. Closing this issue.
