### ISSUE TITLE
World corruption due to ticking entity - thrown shell

### ISSUE THREAD

**Issue by Tobanyi** [Da-Technomancer/Crossroads#235]
**Describe the bug**

**To Reproduce [Optional]**
1.  Put some Expandus/Fusas/i'm guessing any biome-altering material in a shell
2.  Throw shell on ground
3.  Game crashed.

**Expected behavior [Optional]**
Not lock out my world, have a neat biome altering effect I suppose?

**Screenshots [Optional]**
N/A

**Additional context [Optional]**
using most current forge and 1.19.2 published Crossroads version.
Pastebin: https://pastebin.com/8V7z2jmF

**Comment by Da-Technomancer** [comment]
Woops! Sorry about that. 
Just pushed an update (Crossroads 2.9.2, https://www.curseforge.com/minecraft/mc-mods/crossroads-mc/files/4127949) which will fix the issue and let you recover your world.
Fixed as part of commit a4364d1e49bb82df1a3101a3313b596e05e8a5d7.

**Comment by Tobanyi** [comment]
Thanks!
