### ISSUE TITLE
The golden high-throughput hopper and the sorting hopper not added to creative tabs

### ISSUE THREAD

**Issue by MiceStaff** [Da-Technomancer/Crossroads#240]
The golden high-throughput hopper and the sorting hopper is gone in JEI but the item is still craftable

**Comment by Da-Technomancer** [comment]
![image](https://user-images.githubusercontent.com/11035641/186659430-f4d22898-67d3-4fe3-a732-d37656d9b967.png)
What do you mean they're 'gone'?
They're still in the mod.

**Comment by Da-Technomancer** [comment]
This issue only occurs when using a compiled jar. It doesn't happen in a development environment; that's why I couldn't reproduce it before.

**Comment by Da-Technomancer** [comment]
Turns out this bug is caused by Crossroads being installed.
