### ISSUE TITLE
Client-Dedicated Server version issue

### ISSUE THREAD

**Issue by KatoNamus** [Da-Technomancer/Crossroads#243]
**Describe the bug**
When trying to connect to dedicated server with same version installed, MC reports the versions are different even though giving the exact same versions for client and dedicated server.

**To Reproduce [Optional]**
1. Install crossroads-1.19-2.9.3 in client profile.
2. Copy to dedicated server (remove older version if applicable).
3. Start both client and dedicated server, connect to dedicated server.

**Expected behavior [Optional]**
To be able to connect to dedicated server and play Minecraft with crossroads-1.19-2.9.3

**Screenshots [Optional]**
Attached.

**Additional context [Optional]**
~420 mod modpack, if binary troubleshooting is required, it won't happen very soon.
Downgrading both client and dedicated server to crossroads-1.19-2.9.2 gets it running again.
![Minecraft Dedicated Crossroads](https://user-images.githubusercontent.com/447182/219135747-f836052b-54a4-49d3-8671-29d9de126a05.png)

**Comment by Da-Technomancer** [comment]
Fixed with eef725f (2.9.4) on Curseforge.
You'd think by now I'd remember to always test on a dedicated server _before_ pushing an update.
