### ISSUE TITLE
Crash interaction with Ars Nouveau

### ISSUE THREAD

**Issue by Johannason** [Da-Technomancer/Crossroads#263]
Giving Edible Blob to Ars Nouveau "Mycelial Sourcelink" causes irrecoverable crash.

1. Placed Mycelial Sourcelink and Source Jar per Ars Nouveau source-collecting procedure.
2. Dropped Edible Blob (20/20)
3. World crashed. Re-loading world causes immediate crash because conditions are still present.
(4. Update: On 3rd world re-load, Edible Blob was magnetized back into inventory.)

Mycelial Sourcelink is supposed to consume food items and produce Source energy based on the food's values.

(https://pastebin.com/gQE6fm48)

Mod Version: crossroads-1.19.2-2.9.5-PATCH
[Also reported to Ars Nouveau dev]

**Comment by Da-Technomancer** [comment]
Closing, because this is an Ars-Nouveau issue. I've made a PR on their repo that will fix this from their side.
