### ISSUE TITLE
KubeJS fails to load some alchemy reagents

### ISSUE THREAD

**Issue by gamrguy** [Da-Technomancer/Crossroads#266]
**Describe the bug**
When KubeJS loads alchemy reagents, a random quantity of random alchemy reagents fail to load.
Failed alchemy reagents cannot be added to alchemy systems, used in recipes, or viewed as glass/crystal phials in JEI.

**To Reproduce**
1. Install KubeJS
2. Add a script utilizing `ServerEvents.recipes` (does not have to actually add or remove recipes)
3. Open the game and start playing a world
4. Check the logs

**Expected behavior**
All alchemy reagents load without errors.

**Logs**
```
[11:24:44] [KubeJS Recipe Event Worker 0/WARN]: Error parsing recipe crossroads:reagents/vanadium[crossroads:reagents]: {"type":"crossroads:reagents","id":"vanadium","melting":690,"boiling":1750,"item":"crossroads:dusts/vanadium","color":"FFFF00"}: java.util.ConcurrentModificationException
```
https://hastebin.skyra.pw/viqicucumu.yaml

**Additional context**
Mod versions:
crossroads-1.19.2-2.9.5.jar
essentials-1.19-2.15.5.jar
kubejs-forge-1902.6.2-build.33.jar
rhino-forge-1902.2.2-build.280.jar
architectury-6.5.85-forge.jar

**Comment by Random-Scientist** [comment]
looks like a mod loading order issue? Or Crossroads messes with recipes in a loading phase it shouldn't? I'm not very familiar with the Forge loading process but something is probably modifying that recipe when it shouldnt be

**Comment by Da-Technomancer** [comment]
Relevant: https://github.com/KubeJS-Mods/KubeJS/pull/895
