### ISSUE TITLE
Heat conductor crash 

### ISSUE THREAD

**Issue by Cryptix42** [Da-Technomancer/Crossroads#27]
[crash-2016-09-12_16.41.05-client.txt](https://github.com/Da-Technomancer/Crossroads/files/468345/crash-2016-09-12_16.41.05-client.txt)
I have Java 8, I force updated the graphics driver, and as far as I know every type of heat conductor causes this. I tested most of them but I have to recreate the world each time because just the block existing in the world crashes it the moment the first chunk loads. also happens with fluid pipes
[crash-2016-09-12_16.57.12-client.txt](https://github.com/Da-Technomancer/Crossroads/files/468359/crash-2016-09-12_16.57.12-client.txt)
Looks like basically the same error.

**Comment by Da-Technomancer** [comment]
It seems to be a mod incompatibility. It's either both shetiphiancore and multistorage, or it's optifine. I'm guessing it's shetiphiancore and multistorage.

**Comment by Cryptix42** [comment]
Turns out it's optifine, which bums me out a bit because I like optifine, but I can make sacrifices.
