### ISSUE TITLE
Adding wooden gear variants

### ISSUE THREAD

**Issue by RoeDear** [Da-Technomancer/Crossroads#279]
**Scope**
Small-Medium sized mechanic/addition.

**Suggestion**
Adding wooden gear variants that can serve as a weaker/different but cheaper alternative to gears early game. 

**Justification**
It would make it easier to transition to early game rotary power and its machines and give an insensitive to use weaker machines such as the windmill. It would also serve as excellent decoration for bases and factories.

**Impact**
This would slightly impact early game progression and give extra alternatives to metal gears in both early and late game. It would also make it possible to make more rustic looking machines if one is looking for that aesthetic

**Comment by Da-Technomancer** [comment]
a) it was decided early-on in design to not have wooden/stone gears by default, and that decision holds. 
b) If you still want wooden gears for your own use, you can add them to the mod using the config option to add more gear types and making a (small) datapack to add recipes for them.
