### ISSUE TITLE
Mekanism compatibility 

### ISSUE THREAD

**Issue by nohax955** [Da-Technomancer/Crossroads#280]
Scope:
Compatibility

My suggestion:
Mekanism compatibility with its pipes for 1.18.2+.

Why?
 To more easily automate stuff.

The impact:
More players will be willing to try it as Mekanism compatibility will allow easier use of the machinery, a possibility of better compat with other mods, etc.

**Comment by Random-Scientist** [comment]
To clarify, @nohax955 is asking for integration between the Mekanism heat cables/API and crossroads. I'm not sure exactly how similar the APIs for these are, but at a glance they seem relatively similar [see here](https://github.com/mekanism/Mekanism/blob/1.20.4/src/api/java/mekanism/api/heat/).

I'll leave the decision on whether we should actually implement this to @Da-Technomancer

**Comment by Da-Technomancer** [comment]
Duplicate issue to #84
