### ISSUE TITLE
missaligned items in REI GUI

### ISSUE THREAD

**Issue by koostcrashed** [Da-Technomancer/Crossroads#294]
**Describe the bug**
the items and the GUI are missaligned in REI for the detailed crafter recipes.

**To Reproduce [Optional]**
1. open the inventory
2. look up a detailed crafter recipe
with the following mods

**Screenshots**
![image](https://github.com/Crossroads-Development/Crossroads/assets/12761103/9e4a4908-9c26-4366-b987-7761e729023b)

**Additional context [Optional]**
forge 47.3.0
and the following mods
  [✔] architectury-9.2.14-forge
  [✔] cloth-config-11.1.118-forge
  [✔] crossroads-1.20.1-2.10.2
  [✔] essentials-1.20.1-2.16.0
  [✔] Patchouli-1.20.1-84-FORGE
  [✔] REIPluginCompatibilities-forge-12.0.93
  [✔] RoughlyEnoughItems-12.1.725-forge

**Comment by Random-Scientist** [comment]
Crossroads does not directly support REI or REIPluginCompatibilities. This issue is an REIPluginCompatibilities bug, since these recipes render correctly with JEI.
