### ISSUE TITLE
Crash with Optifine 

### ISSUE THREAD

**Issue by WildKarrade** [Da-Technomancer/Crossroads#31]
When placing a fluid pipe with optifine installed I get this crash-log. While I know optifine typically isn't "officially supported" in most cases, I would still recommend at least seeing if it's on their end or yours because a lot of people use it currently, especially in fastcrafts current updating absence.

http://pastebin.com/cpcLMbkp

**Comment by Da-Technomancer** [comment]
I've already known about this bug, but I haven't reported it to the Optifine dev(s) yet, because I *think* it's on their side, but I'm not sure. I'll report it to the Optifine dev(s) to be safe and find out if it's something I need to fix.

**Comment by WildKarrade** [comment]
Alright, awesome concept for a mod btw :P

**Comment by Da-Technomancer** [comment]
I've managed to fix the bug. It will be in the next update, which I'm sorry to say might not be out for a few more weeks.
