### ISSUE TITLE
Fluid Pipe Crash with Mekanism Fluid Tank

### ISSUE THREAD

**Issue by FallenEagle1** [Da-Technomancer/Crossroads#37]
Crossroad Version: 1.10.1-2.0.2
Mekanism Version: MekanismAll-1102-921 homebaked

Pastebin: [http://pastebin.com/pN3AM8Hm](url)

Crash was in the modpack "All the Mods". I had a basic fluid tank from mekanism that I attached to a fluid pipe. Several scenarios were tested:

If fluid was in the tank when the pipe was being attached, there would be a crash.

Pipes could be attached to the tank as long as no fluids were present.

Once attached, the game would crash if fluid was added to the tank.

This was done primarily with lava, but is also happens with water.

**Comment by Da-Technomancer** [comment]
So I've looked into it and it seems to be on Mekanism's side. For that reason I'm guessing this happens with a few other Mekanism blocks to. Thanks for reporting this, I'll let the Mekanism dev know.
