### ISSUE TITLE
Minetweaker grindstone input ignores metadata.

### ISSUE THREAD

**Issue by al132** [Da-Technomancer/Crossroads#42]
Hello again, i've been trying to use the minetweaker support for the grindstone, but unfortunately it seems no matter what I put into the input, the metadata is ignored, and the item/block with meta 0 will be inserted. I'm not sure if there is supposed to be ore dictionary support for the input slot, but if there is, then that isn't working either.

Thanks,
al132

**Comment by Da-Technomancer** [comment]
The metadata thing is a known bug caused by how the grindstone stores recipe ingredients as a string, but I already had a change planned that would fix this. However, I'm not having any problem with the ore dictionary. That is supposed to work, and in fact it works fine for me. Could you send me the specific script using ore dictionary that wasn't working?

**Comment by al132** [comment]
It looks like after further testing that the ore dictionary does actually work, I just assumed that it didn't because the recipe showed up as an empty recipe in JEI. Even if I disable all of my grindstone recipes, the default copper ore recipe still shows up as empty recipe.

**Comment by Da-Technomancer** [comment]
What exactlydo you mean by empty recipe in JEI? You are the second person to report that, and I still don't know what that means.

**Comment by al132** [comment]
![capture](https://cloud.githubusercontent.com/assets/16395640/19689474/22090e24-9a93-11e6-8c91-c87a78427616.PNG)

**Comment by Da-Technomancer** [comment]
Currently there seems to be some sort of bug where no tweaker recipes are shown in JEI (even vanilla crafting table ones with just crafttweaker and JEI installed). I'm guessing this is related, so I'll wait for that bug to get patched before trying to fix the blank recipes.

**Comment by al132** [comment]
well, this is true of JEI versions 329 (and higher I assume), but even in JEI version 328 where all the other recipes are working this issue is still here and I haven't seen it with any other mods.
