### ISSUE TITLE
Issue with Sponge

### ISSUE THREAD

**Issue by lilmoefow** [Da-Technomancer/Crossroads#43]
SpongePowered/SpongeForge#1017

Reporting here aswell to see if you have any input on the issue.

**Comment by Da-Technomancer** [comment]
I know very little about Sponge (all I know is what I read on the about page) but I can tell you that the only way this bug could occur is if Sponge either makes a MAJOR change to itemstacks (which I highly doubt) or if it makes a change that makes
`!playerIn.capabilities.isCreativeMode`
return false even in survival. However, everything I just said is invalid if the item is only not consumed on the client side, though from your description this is happening on the server side as well. I'll keep looking into this, but does this happen with large and toggle gears as well, or just normal gears?

**Comment by lilmoefow** [comment]
ill test all gears right now, so far we have only been testing it with the Iron Gears specifiaclly

**Comment by lilmoefow** [comment]
When Placing Large Gears, the Gear is placed but you still keep on in your inventory.  Once broken you get a duplicate of the large gear, and 64 Misc Metal Scrap

When placing the Toggle Gears, it places properly and it removes it from your inventory.  When broken it gives you the Toggle gear back and 6 Misc Metal Scrap

**Comment by Da-Technomancer** [comment]
In that case, something is seriously wrong. The toggle gear does not, and never has, contained any code which even refers to Misc Metal Scraps (large gears do, but that's another matter). Large gears should only be dropping scraps when broken by explosions.

**Comment by lilmoefow** [comment]
if there is any think else i can provide to help, let me know.

**Comment by Da-Technomancer** [comment]
Are you sure the toggle gear dropped 6 scraps and large gears 64? Because if anything (and it should be none), the toggle gear would drop 0 scraps and large gears would drop 70. Could you try again and just make sure those 6 came from the toggle gear weren't from the large gear?

**Comment by lilmoefow** [comment]
Alright, Yeah you are right. The toggle gear drops fine, and the large one is giving the 70 scrap.

**Comment by Da-Technomancer** [comment]
The code that places the gear in the world, and the code that drops metal scrap are not connected. The placing code is only in the item, and the scrap code is only on the block form of the gears, and the two pieces of code never call each other. Either those two things both being broken is a coincidence, or their is an obscure connection I am missing. Neither of those things are broken without sponge. I'm going to be honest, solving this one is going to take a while to figure out, so don't expect a fix to come out any time soon. In the meantime, let me know if you find anything else broken when using sponge.

**Comment by lilmoefow** [comment]
Just want to update this issue to say that it is still present with these versions

forge-1.10.2-12.18.2.2123-universal.jar
spongeforge-1.10.2-2123-5.1.0-BETA-1914.jar
crossroads-1.10.2-1.1.8.jar

**Comment by Da-Technomancer** [comment]
I think this may be fixed now. Could you please verify if this issue still exists with the latest version of Crossroads?

**Comment by lilmoefow** [comment]
Sorry, I just don't have that server set up right now to be able to test it.  The player count fell off pretty hard on that server with official packs coming out.  If i get a chance i will rehost it on a separate box to test for you.

**Comment by Da-Technomancer** [comment]
As no one has reported this bug as still being present, I have no way of testing the bug myself, and from looking at the code what I changed should have fixed it, I am closing this issue. If the bug is found to still exist, it will of course be reopened.
