### ISSUE TITLE
Gears only seem to place in 1 direction

### ISSUE THREAD

**Issue by darkphan** [Da-Technomancer/Crossroads#45]
Testing in single player and server, but gears only seem to be able to place in a single direction.

Crossroads version 1.1.8

**Comment by Da-Technomancer** [comment]
Which direction is that (you can check cardinal direction in f3)? Are you using sponge or is this a normal modded environment?

**Comment by darkphan** [comment]
Here is a screenshot of what I am talking about, no matter what face you click on the gears place the same way. This is on a normal modded environment (forge 12.18.2.2125)

http://puu.sh/smqH2/fd9b808ca9.png

**Comment by darkphan** [comment]
After looking at things again, it seems JEI is somehow hiding the normal gears, and only showing the large and toggle ones.
