### ISSUE TITLE
Steam power mod interaction unusable

### ISSUE THREAD

**Issue by CJL48** [Da-Technomancer/Crossroads#50]
When I try to create a steam power setup in my instance, steam will not enter the turbine/radiator, and the boiler will eventually stop outputting steam into the pipes. I have not tested this bug with other fluids, but I believe that this is unique to the steam power blocks. With ONLY forge, crossroads, and dependencies in an instance, newly placed steam turbines and radiators work just fine. Said turbines continue to function when other mods are added to the instance, without disturbing the steam setup. I apologize for not being able to say which mods are responsible for this bug, but I found out that already placed turbines would continue to function while trying to discover that.

I am using:
Minecraft 1.10.2
Forge 12.18.3.2185
Crossroads 1.3.2
full mods list: [mods.txt](https://github.com/Da-Technomancer/Crossroads/files/697962/mods.txt)

**Comment by Da-Technomancer** [comment]
When you say "the boiler will eventually stop outputting steam into the pipes", do you mean the pipe is filling up, or that that the boiler stops producing steam? If the boiler stops producing steam, then you are likely using normal water instead of distilled water, thus clogging the boiler with salt. Also, make sure you are trying to insert into the correct sides. Turbines and radiators only accept steam from the bottom. Nothing in your mod list should be interfering with this at all.

**Comment by CJL48** [comment]
When I say the boiler will eventually stop outputting steam into the pipes, I mean that the pipe stays mostly empty, and the boiler fills up with steam. This occurs even with distilled water, so it's not the salt mechanic, and the pipes are feeding into the bottom. The same setup that works with only crossroads installed, will NOT work if I build it in an instance that has all of my mods installed.

**Comment by Da-Technomancer** [comment]
Could you post a picture of the exact setup you are using so I can try to reproduce the bug with those mods?

**Comment by CJL48** [comment]
Yes, here is a picture a setup that I believe should work. If there is something wrong with it, let me know. (The red output of the turbine is closest to the camera)

![2017-01-11_20 07 51](https://cloud.githubusercontent.com/assets/8433790/21873040/de461756-d839-11e6-9dcf-f16eed4a2ef2.png)

**Comment by Da-Technomancer** [comment]
I've discovered this is an incompatibility with Mekanism. I'll keep looking into this.

**Comment by CJL48** [comment]
Thanks. Do you want me to make an issue with the Mekanism github?

**Comment by Da-Technomancer** [comment]
No, I need to keep looking into this to find out exactly what the cause is.

**Comment by Da-Technomancer** [comment]
I found the problem, and it's on Crossroad's end. It's caused by Mekanism and Crossroads both adding steam. I'll fix it immediately.
