### ISSUE TITLE
Crash upon breaking large gear.

### ISSUE THREAD

**Issue by CelticChristoph** [Da-Technomancer/Crossroads#53]
Hey there, got another one for ya regarding large gears. D:

MC version: 1.10.2
Forge version: 12.18.3.2221

Was moving around a large gear to experiment with gear usage (this is when my friend had #52 happen), I was able to place/removed the large gear a few times. But on the 3 or 4th time breaking the gear to pick it up, it crashed my client. It seems like a different reason from my friends crash, but they both seem related to a rendering call or something? I'm not sure.

Crash report:
http://pastebin.com/CMYhtMZ1

**Comment by Da-Technomancer** [comment]
This bug has popped up with a few different things, and each time it has been fixed. The problem with finding it though is that it only occurs in multiplayer when there is a slow connection, which means I can't test this fix. I'll link you the update, and please let me know if that fixes it. It should though,

**Comment by Da-Technomancer** [comment]
https://minecraft.curseforge.com/projects/crossroads-mc/files/2371779
