### ISSUE TITLE
Better Creative Mode support - do not drop item versions of multitile blocks (e.g. Large Gears) if broken while in creative

### ISSUE THREAD

**Issue by Barhandar** [Da-Technomancer/Crossroads#54]
In creative where all blocks are at your fingertips, anything dropping on break is an annoyance and messes with hotbar/inventory.

**Comment by kane-thornwyrd** [comment]
You can use the appropriate gamerule doTileDrop false :)

**Comment by Da-Technomancer** [comment]
I'll fix this in the next major update.
