### ISSUE TITLE
Crash with McJty The One Probe

### ISSUE THREAD

**Issue by BuggaNoia** [Da-Technomancer/Crossroads#55]
Placing a Salt Reactor with a fluid pipe to an "Cooking for Blockheads Sink" (Infinity water source) results in a fluid pipe that reports a too big fluid quantity to "The One Probe": TOP tries to show a fluid bar that leaves the screen on the right side and put the game in an endless loop

Pack: All The Mods Expert 1.0.23
Crossroad Version:  crossroads-1.10.2-1.3.5
The One Probe Version: theoneprobe-1.1x-1.4.1

**Comment by Da-Technomancer** [comment]
Could you post a crashlog?

**Comment by Da-Technomancer** [comment]
Actually, after looking through the code for Cooking for Blockheads and the pipe, I've worked out the problem, and it's on Cooking with Blockheads' end. I'll take care of reporting it.
