### ISSUE TITLE
FluidCoolingChamberTileEntity#hasCapability wrongly returns true, creating compatibility issues

### ISSUE THREAD

**Issue by pau101** [Da-Technomancer/Crossroads#56]
A pair of parentheses is missing in the following expression starting at line 123:
```java
if (capability == Capabilities.HEAT_HANDLER_CAPABILITY && facing == EnumFacing.UP || facing == null) {
	return true;
}
```
Corrected:
```java
if (capability == Capabilities.HEAT_HANDLER_CAPABILITY && (facing == EnumFacing.UP || facing == null)) {
	return true;
}
```
This logical error is the cause to pau101/Fairy-Lights#19.

**Comment by Da-Technomancer** [comment]
Yes. I actually found and fixed this yesterday (proof: commit history) but it was on the 1.11 branch. This seems major enough for me to backport it though.
