### ISSUE TITLE
Inconsistent movement speed while using the Prototype Watch

### ISSUE THREAD

**Issue by Da-Technomancer** [Da-Technomancer/Crossroads#60]
Currently while using the Prototype Watch (and by using I mean holding down right mouse) the player is slowed, as when using any other usable item (like a bow). However, whenever the needle changes, or for that matter the NBT determining the exact angle of the needle is changed, the slowdown effect pauses, speeding the player up. In effect, a watch design where the needle continuously spins will let the player move faster than one which doesn't. I would be happy with either the player being slowed regardless of the needle, or the player moving full speed regardless of the needle, but this inconstancy is a bug.

I will record here some relevant information on my attempts to fix this bug, in order to aid anyone else trying to help. It appears that in vanilla, this speed change can occur any time the held item is changed during use EXCEPT the initial click, as that method returns (as well as an EnumActionResult) an ItemStack. No other relevant method does this. Due to how the needle works, only changing it when the item is first right clicked does not suffice. I thought that perhaps the speed reset was due to the use timer being reset to 0, so I used reflection to change the use timer (in the player) to other values. This had no helpful effect. Nor did sending a packet to the client with the new ItemStack to set the held item there as well, thinking this was an input issue handled on the client side. No effect. The method in Item shouldCauseReequipAnimation does something else entirely, so that didn't work either. I am currently of the belief that there are only 3 ways this problem will ever be fixed, that either something in base Minecraft changes, that Forge adds something, or a coremod. I am not willing to make Crossroads a core mod. If anyone finds a way to fix this without a coremod, please help (either by creating a pull request or by providing information in a comment to this issue).

**Comment by CTH999** [comment]
I don't know if this will work, but I may have come up with a temporary solution. Since all players have a base movement speed attribute, would it be possible to modify it using the mod to slow them down when the item stops slowing them? I found on the wiki that While sneaking, the speed is 1.31 Blocks Per Second, and while not sneaking, it's 4.3 Blocks Per Second with the base of 0.1. So, I took the equation, and found that by subtracting 0.06916, It should lower their speed to 1.3102 Blocks per second. Since I don't know much about modding yet, I don't know if it will work, but I figured I would tell you and see if it would even be possible.

**Comment by Da-Technomancer** [comment]
I've looked into that, and the only reason it doesn't work is that dynamically modifying the attributes actually makes the problem worse, because then while the attribute is being changed, the item also has no effect on movement speed at that time either.

**Comment by CTH999** [comment]
Huh, I just knew about attributes from commands. I'm wonder though, how did you trigger altering their attribute?

**Comment by CTH999** [comment]
I thought of something, If it would need a core mod, what about making it to where crossroads is the core mod. Basically, You fix the problem with another mod, and it could be not required, but recommended. It would fixe any non-game breaking features that would be very hard to fix, maybe possible, but hard. That way, you have it easier, no core mod, and people can download it. I don't know if this would work, It's just a possibility. If I think of any other solutions I'll tell you

**Comment by Da-Technomancer** [comment]
Fixed in the Schism Update
