### ISSUE TITLE
Creation Chamber

### ISSUE THREAD

**Issue by SilkenStrand** [Da-Technomancer/Crossroads#63]
I seem to have stumbled into infinite copper. I put a copper ingot in a grinder, through two sorting hoppers into a heating crucible, through 1 tube into the creation chamber, then out another tube into a cooling chamber, and it just keeps pouring.

**Comment by Da-Technomancer** [comment]
Is the cooling chamber connected to the top port of the creation chamber or the bottom?

**Comment by SilkenStrand** [comment]
The bottom.

**Comment by Da-Technomancer** [comment]
This is now fixed in the latest version on curse. Thank you for the report, it turned out to be an issue with fluid tubes in the end.
