### ISSUE TITLE
Cables not connecting

### ISSUE THREAD

**Issue by joneugster** [Da-Technomancer/Crossroads#66]
Heat cables and fluid tubes seem not to connect at all (see picture). Using v1.12-1.6.3 together with forge 14.22.1.2478
Can you help me what I'm doing wrong...

![2017-10-28_21 22 01](https://user-images.githubusercontent.com/9141564/32137821-890ebcb6-bc27-11e7-8189-c30509ddb9b3.png)

**Comment by Da-Technomancer** [comment]
From the picture, it looks like you are using redstone heat cables & redstone fluid tubes. Those only connect when given a redstone signal. For normal use, you should be using the heat cables and fluid tubes that don't have redstone in the name.
