### ISSUE TITLE
Can't Unlock Technomancy

### ISSUE THREAD

**Issue by 666lumberjack** [Da-Technomancer/Crossroads#70]
I have Time discovered (pulsed a beacon harness using a button as you show in the video guide because I'm trying to do creative mode testing) as well as the three basic elements in case those are required as well. I place down a Detailed Crafter and place a bronze gear in each slot and nothing happens. 

Using Crossroads 1.6.3 and Forge 2540

**Comment by 666lumberjack** [comment]
Looks like it's because I unregistered Crossroads gears from the OreDict. Not sure if that's something you want to change?

**Comment by Da-Technomancer** [comment]
The unlocking technomancy recipe uses the oreDict bronzeGear, which means any mod's bronze gears should work. That also means removing crossroads bronze gears from the oreDict makes them not work for the unlocking. Working as intended.
