### ISSUE TITLE
CTD when commanding Mechanical Arm to place blocks

### ISSUE THREAD

**Issue by 666lumberjack** [Da-Technomancer/Crossroads#71]
Log: https://paste.ee/p/Q8jMt

**Comment by Da-Technomancer** [comment]
This appears to be an incompatibility with FTBUtilities (the bug is on the Crossroads end). It will be fixed in the next Crossroads version, but in the meantime either uninstalling FTBUtilities or unclaiming the chunk the arm is placed in should fix it.
