### ISSUE TITLE
Never Mind

### ISSUE THREAD

**Issue by CTH999** [Da-Technomancer/Crossroads#73]

**Comment by Da-Technomancer** [comment]
This is absolutely not the right place for that sort of suggestion. If you want to suggest that, in the future please use a different platform (such as youtube comments), as github is not a message service. I don't have the time to make a java tutorial series even if I wanted to, but I can recommend a good coding tutorial: https://thenewboston.com/videos.php?cat=31

**Comment by CTH999** [comment]
Sorry.

**Comment by CTH999** [comment]
I'm sorry. Are there ways to delete issues? If you can, please delete this.

**Comment by CTH999** [comment]
Thank you Da-Technomancer

As of writing this, I have been part of GitHub for 4 Days. So, thank you for telling me that That was incorrect. I didn't realize it, so now that I do, I won't end up doing it again.

I'm sorry for the inconvenience of putting it here.

Sincerely- CTH999
