### ISSUE TITLE
[1.12.2] Very strange crash

### ISSUE THREAD

**Issue by KAfable** [Da-Technomancer/Crossroads#76]
I have Crossroads in a very large pack I'm developing and got the following crash report:

https://hastebin.com/nitoquhumo.sql

The reason why it's strange was because there were no crossroads blocks placed in world or items involved I was testing [Powered Thingies](https://minecraft.curseforge.com/projects/powered-thingies) Animal Farmer, and then throwing Thermal Foundation Morbs to capture the new mobs, when it crashed with the following report.

**Comment by Da-Technomancer** [comment]
It would appear the Thermal Expansion Morbs do something a bit weird in the entity code that I hadn't expected. I've now fixed it, and it will be released in the next version. In the meantime, don't throw Thermal Foundation Morbs. Florbs should work though.
