### ISSUE TITLE
Sorting hopper changes ores in the grindstone

### ISSUE THREAD

**Issue by jinkhya** [Da-Technomancer/Crossroads#77]
**MC** : 1.12.2
**Crossroads version** : crossroads-1.12-1.6.5
**Forge** : 14.23.2.2623
**Modpack** : Interaction 0.17

**Blocks involved** : grindstone and sorting hopper

**Description of the issue :** 
Ores placed in a sorting hopper next to a grindstone replaces the nature of the ore already in the grindstone. 
Here is a video of the [issue](https://streamable.com/hb4n0)

A normal hopper doesn't do it, just the sorting hopper. 
Thanks in advance! :)
Jin

**Comment by KAfable** [comment]
This error also seems to occur with [Wopper](https://minecraft.curseforge.com/projects/wopper) as well as shown by this link: https://streamable.com/by7hv
