### ISSUE TITLE
Laser with no lens turns blocks into Redstone Blocks

### ISSUE THREAD

**Issue by ofseaandstars** [Da-Technomancer/Crossroads#79]
Using the Arcane Extractor with coal/redstone in it and firing a laser with no lens on it will cause certain blocks to turn into `Block of Redstone`.

What I would expect to happen:
Lightning strikes, the area is set on fire, but blocks remain the same.

What actually happens:
Lightning strikes, the area is set on fire, but certain blocks become blocks of Redstone.

Current list of blocks affected (that I've found so far):

- Vanilla Furnace
- Vanilla Enchanting Table
- Arcane Reflector
- Lens Holder (sideways)
- Dispenser
- Dropper
- Observer

**Versions**
Crossroads: 1.6.5
Forge: 14.23.2.2640

**Comment by Da-Technomancer** [comment]
This isn't a bug. It's literally part of what the charge element does (see the relevant section in the manual, under elements). It turns any rock material block (that doesn't receive beams) into a redstone block.
