### ISSUE TITLE
Request: Crafttweaker support for envirHeatSources 

### ISSUE THREAD

**Issue by Saereth** [Da-Technomancer/Crossroads#80]
how would you feel about adding craftTweaker support for configurable envirHeatSources, Also if this isnt something you'd be interested in doing yourself what's your policy on pull requests? I could possibly work on a bit, could add alot of nice options for pack makers.

**Comment by Da-Technomancer** [comment]
1. I'm fine with adding CraftTweaker support for that. It won't take long for me to add at all. Expect it as part of the next update (Alchemy update, no current ETA). 

2. The policy on pull requests is that pull requests are accepted. However, pull requests that don't meet short format guide in the README.md file will probably be denied, as fixing someone else's formatting tends to take longer than just doing it myself.

**Comment by Saereth** [comment]
That's great news, looking forward to it, thanks! Yeah I hear ya on dealing with reformatting PRs, such a pain.
