### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Da-Technomancer/Crossroads#81]
MC: 1.12.2
CR: 1.12.2-1.7.0
Forge: 14.23.3.2681

[Log](https://pastebin.com/iQbMh7nm)

**Comment by Da-Technomancer** [comment]
You seem to have cut out the second half of the log. What version of JEI are you using (if any)? I think I've found the issue, it seems I accidentally made JEI a dependency. I'll have a fix out in a few minutes, until which time just adding JEI should fix it.

**Comment by ProxyPlayerHD** [comment]
JEI was already installed before i even put CR in. Version 4.9.1.175

**Comment by Da-Technomancer** [comment]
This should definitely be fixed in 1.7.2 now.
