### ISSUE TITLE
Strange hopper behaviour

### ISSUE THREAD

**Issue by th4umiel** [Da-Technomancer/Crossroads#83]
I assume that there is no problem when using the sorting hopper instead of a normal hopper when pushing items in a machine (but please, correct me if I'm wrong). 

When a furnace was smelting some item, I put few stack of copper dusts to smelt in a chest over the sorting hopper. The hopper extracted one item at a time from every stack in the chest but these dusts extracted weren't in the hopper or in the furnace, so I'm really confused: basically they disappeared into thin air. 

Now I'm trying to reproduce this behaviour but in the meantime can you look into this?

EDIT: can confirm, it's likely a bug. I put various items in the chest above the hopper, when substituting one of these items in the hopper buffer, it fills the hopper with the new item while voiding some of the others (stacks of them, so it's pretty serious)

**Comment by Da-Technomancer** [comment]
Which Crossroads version are you on? Full version number please (example: 1.7.2 or 1.6.5)

**Comment by th4umiel** [comment]
Tested with 1.7.1, I need to test with 1.7.2

**Comment by Da-Technomancer** [comment]
I'm having trouble reproducing this bug at all. Would you mind giving me step by step instructions to trigger it for testing? I think I'm interpreting your earlier instructions wrong.

**Comment by th4umiel** [comment]
It happens also with 1.7.2
Put one sorting hopper below a furnace, one above. Over the one above, put a chest. Fill the furnace for e.g. sand, the hopper above, with sand and put e.g. logs or other smeltable in the chest (simulating the already full buffer of the hopper). English is not my first language, so if I'm still not clear let me know :)

**Comment by Da-Technomancer** [comment]
I've now confirmed this bug, it will be fixed next update. It seems this bug slipped through as it only applies when using a mix of 2 or more items types. The furnace isn't required to reproduce it, only having a full sorting hopper drawing from a chest with a different item is required.

**Comment by Da-Technomancer** [comment]
Fixed in the Schism Update
