### ISSUE TITLE
Missing Fluid Texture with tinker Contruct

### ISSUE THREAD

**Issue by Diamssword** [Da-Technomancer/Crossroads#85]
Hello, just realized that all molten ore textures (iron, copper gold and tin) are missing when Tinker construct is installed.
The tinker mod don't add any alternative molten ores for thos fluids.
Texture are missing on tank, crucible, bucket and JEI recipes but work when placed on world.
I haven't seen any missing texture report on logs.
![image](https://user-images.githubusercontent.com/21200137/41657044-458dbd56-7492-11e8-8f4f-780a44897b5a.png)

**Comment by Da-Technomancer** [comment]
Thank you for your bug report, I'll look into it.

**Comment by Diamssword** [comment]
Thank you :)

**Comment by Da-Technomancer** [comment]
I've been unable to reproduce this issue with only Crossroads and Tinker's installed 
![cannot reproduce](https://user-images.githubusercontent.com/11035641/42060641-7c88e146-7af5-11e8-856e-bb4188dc4e9a.png)

Could you attach a full modlist? Simply sending me a startup log from the pack this happened in will have a modlist inside it.

**Comment by Da-Technomancer** [comment]
Closed due to inactivity and inability to reproduce
