### ISSUE TITLE
Removing recipes from the grindstone using crafttweaker does not work

### ISSUE THREAD

**Issue by lobbienjonsji** [Da-Technomancer/Crossroads#86]

**Comment by Da-Technomancer** [comment]
Apologies for the unusually late response. 

You've not included any information about this issue other than the title. Could you please comment with the **exact** line in the CraftTweaker script that you claim isn't working? It's possible that you've just used the integration incorrectly. Also, linking the log that CraftTweaker itself spits out wouldn't be amiss. As soon as I get the necessary clarification, I'll get right on it.
