### ISSUE TITLE
Issue with dialing coordinates on Workspace Dimension Gateways

### ISSUE THREAD

**Issue by MrDrProfNo** [Da-Technomancer/Crossroads#92]
Hi! I've been messing around with the Workspace Dimension portals, and seem to have run into a wall.

I don't think this is me missing something stupid. My in-game experiences are contradictory to material on the subject that I can find, and if things are working as intended... then I can't work out how to use them. 

My current resources on this are the in-game book (primarily the Technicians Manual, though on cursory glance the entries for the Workspace dimension seem to be the same in the Mysterious Journal), and [this video](https://www.youtube.com/watch?v=yiVZu0wF1Zg).

I'm running:
Minecraft 1.12.2
Minecraft Forge 14.23.3.2655
Guide-API 1.12-2.1.7-62
essentials-1.12.2-1.2.0
crossroads-1.12.2-1.11.0
CraftTweaker2-1.12-4.1.9

(Summary: Whatever was up-front for the given version of Minecraft as of ~3 weeks ago)

So.

I set up the gateway frames in the overworld. I'd initially gone off the description in the book, and actually *misread* it, resulting in me producing the only working variant of the gateway that I've managed: I fired a rift beam into the *front* of the top frame block. It produces the Gateway, everything is fine. Firing into the top of the Gateway frame behaves as though it were being fired into any solid block. This is also not how it's done in the video.

I noticed that you can adjust the dimensions of the portal in the overworld, so there's gears there in the attached save file, but it doesn't do anything as expected.

So, I go through. I'm in the workspace dimension. I set up the gateway and attach the gears to return, and discover that placing a gear on the top of the upper Gateway Frame block modifies the X coordinate. No other sides of it modify the coordinates at all. No placement of gears on the other gateway frames can illicit a change in any of the coordinates. The displayed coordinates when using goggles/multimeter are approximately the ones it sends you to in the overworld. 

For reference in the attached save:
The spawnpoint is approximately at 115, 65, 150
There's a pair of goggles with quartz lens in the chest

(not sure how uploading files on github works, so here goes...)
[Workspace Dimension Problem Demo.zip](https://github.com/Da-Technomancer/Crossroads/files/2362859/Workspace.Dimension.Problem.Demo.zip)

**Comment by Da-Technomancer** [comment]
That the Gateway Frame only accepts beams from the sides of the top frame block is not a bug, the video is outdated. It was changed in the Schism update so that the gear on top of the gateway controls the y, instead of the gear going on the front. 

However, it would appear the Schism update did add the bug where gears aren't updating the coordinates properly, as you've noticed. The next update will fix this.
