### ISSUE TITLE
[Suggestion] Visual suggestions for the beam system

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#93]
- Make them support partial ticks, currently the animation for beams is very choppy. All you need to do is `renderAngle = currAngle * (1-partialTicks) + nextAngle * (partialTicks)` (where you can obviously easily calculate nextAngle as beams have constant angular velocity). I think gears already do this aswell.
- It could also be cool to have beams gradually widen or get slimmer using partialTicks aswell.
- Beams that are especially girthy clip through the block they're passing through, which can be helpful sometimes if you don't have an omnimeter and you have a fully opaque beam system but also looks unspeakably ugly and all 3 base elemental materials (coal, redstone, salt) make beams that have the exact size to look like that.

**Comment by Da-Technomancer** [comment]
As this is applied in the betas (other than the contracting/expanding suggestion), I'm closing this.
