### ISSUE TITLE
Snow lands on gears, axles and probably a hundred other things

### ISSUE THREAD

**Issue by DaedalusGame** [Da-Technomancer/Crossroads#95]
![grafik](https://user-images.githubusercontent.com/9559216/46565538-94541c00-c910-11e8-9f6e-150f509e81f1.png)

I believe this is caused by your blocks not implementing `Block::getBlockFaceShape` and thus defaulting to all sides being solid. This has some other strange artifacts besides snow, like levers and torches sticking to what appears to essentially be thin air.

**Comment by Da-Technomancer** [comment]
Noting for the record that this bug is fixed in the 1.13 branch with rotary devices migrating to the "Mechanism" block internally, which does override `Block::getBlockFaceShape` properly.
